# Generated by Django 4.0.4 on 2022-05-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageconfirmationmodel',
            old_name='message_id',
            new_name='message',
        ),
    ]
