# Generated by Django 4.0.4 on 2022-05-11 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0003_messagemodel_status_delete_messageconfirmationmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='status',
        ),
        migrations.CreateModel(
            name='MessageConfirmationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('r', 'review'), ('b', 'blocked'), ('c', 'correct')], default='r', max_length=50)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messagesapp.messagemodel')),
            ],
        ),
    ]
