# Generated by Django 4.0.4 on 2022-05-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0004_remove_messagemodel_status_messageconfirmationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='status',
            field=models.CharField(choices=[('r', 'review'), ('b', 'blocked'), ('c', 'correct')], default='r', max_length=50),
        ),
        migrations.DeleteModel(
            name='MessageConfirmationModel',
        ),
    ]
